// <auto-generated />
using System;
using DespensaBarrialFinal.BD.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepensaBarrialFinal.BD.Migrations
{
    [DbContext(typeof(AplicacionDbContext))]
    partial class AplicacionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Administrador", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("NumeroTelefono")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Administrador");
                });

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Categorias", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int>("CodigoCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("ProductosId")
                        .HasColumnType("int");

                    b.Property<string>("TipoCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductosId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Deposito", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int>("Unidad_minima")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Deposito");
                });

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Empleado", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int>("DNI")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("EdadEmpleado")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("NumeroTelefono")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DNI" }, "EmpleadoDNI_UQ")
                        .IsUnique();

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Productos", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("DepositoId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("FechaVencimientoProducto")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("PrecioProducto")
                        .HasMaxLength(3)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepositoId");

                    b.HasIndex("NombreProducto")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Proveedores", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int>("AdministadorId")
                        .HasColumnType("int");

                    b.Property<int?>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumeroTelefono")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.Property<int?>("ProductosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("ProductosId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Categorias", b =>
                {
                    b.HasOne("DespensaBarrialFinal.BD.Datos.Entidades.Productos", "Productos")
                        .WithMany("Categorias")
                        .HasForeignKey("ProductosId");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Productos", b =>
                {
                    b.HasOne("DespensaBarrialFinal.BD.Datos.Entidades.Deposito", null)
                        .WithMany("Productos")
                        .HasForeignKey("DepositoId");
                });

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Proveedores", b =>
                {
                    b.HasOne("DespensaBarrialFinal.BD.Datos.Entidades.Administrador", "Administrador")
                        .WithMany("Proveedores")
                        .HasForeignKey("AdministradorId");

                    b.HasOne("DespensaBarrialFinal.BD.Datos.Entidades.Productos", null)
                        .WithMany("Proveedores")
                        .HasForeignKey("ProductosId");

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Administrador", b =>
                {
                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Deposito", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("DespensaBarrialFinal.BD.Datos.Entidades.Productos", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Proveedores");
                });
#pragma warning restore 612, 618
        }
    }
}
